---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: templates
  label: Templates
  create: documents
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: json
upload_dir: media
public_path: https://raw.githubusercontent.com/pdx-mission/give-app-data/master/media
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
